app/web/feedback/urls.py
from .views import *
from django.urls import path


urlpatterns = [
    path('', FeedbackFormView.as_view(), name='feedback'),
]

app/web/urls.py
from django.conf import settings
from django.urls import path, include as path_include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from web.core.views import *
from web.health.views import health_default, health_db
from web.users.views import generic_logout, generic_login
from django.views.generic import TemplateView
from django.conf import settings
from web.users.views import OIDCAuthenticationRequestView
from .routers import router
from django.views.generic import RedirectView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('data/', DataView.as_view(), name='data'),
    path('admin/settings', VariablesView.as_view(), name='variables'),
    path('admin/dumpdata', dumpdata, name='dumpdata'),
    path('admin/objectstore', ObjectStoreView.as_view(), name='objectstore'),
    path('admin/sendmail', SendMailView.as_view(), name='sendmail'),
    path('admin/login/', RedirectView.as_view(url='/oidc/authenticate/'), name='disabled_login'),

    path('health', health_default),
    path('omslagroute/health', health_default),
    path('omslagroute/health-db', health_db),

    path('document/', path_include('web.documents.urls')),
    path('timeline/', path_include('web.timeline.urls')),
    path('organisaties/', path_include('web.organizations.urls')),
    path('gebruikers/', path_include('web.users.urls')),

    path('clienten/', path_include('web.cases.urls')),
    path('feedback/', path_include('web.feedback.urls')),

    path('inloggen/', generic_login, name='inloggen'),
    path('uitloggen/', generic_logout, name='uitloggen'),

    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('404', TemplateView.as_view(**{
            'template_name': '404.html',
        }), name='sendmail'),
    ]

if settings.IAM_URL:
    urlpatterns += [
        url(r'^oidc/', include('keycloak_oidc.urls')),
        path('inloggen/', OIDCAuthenticationRequestView.as_view(), name='inloggen'),
    ]
if settings.BRANCH_NAME != 'production':
    urlpatterns += [
        path('user-meta/', TemplateView.as_view(
            template_name="user_meta.html",
        ), name='user_meta'),
    ]

app/web/feedback/forms.py
from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField(
        label='Naam',
        required=False,
    )
    email = forms.EmailField(
        label='E-mailadres',
        required=False,
    )
    feedback = forms.CharField(
        label='Wat wil je ons laten weten',
        required=True,
        widget=forms.Textarea(
            attrs={
                'rows': 4,
            }
        ),
    )

app/web/feedback/views.py
from django.views.generic import FormView
from .forms import *
from constance import config
from django.http.response import HttpResponseRedirect
import sendgrid
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from sendgrid.helpers.mail import Mail
from django.template.loader import render_to_string


def validate_email_wrapper(email):
    from django.core.validators import validate_email
    from django.core.exceptions import ValidationError
    try:
        validate_email( email )
        return True
    except ValidationError:
        return False


class FeedbackFormView(FormView):
    form_class = FeedbackForm
    template_name = 'feedback/feedback.html'
    success_url = '.?send=1'

    def form_valid(self, form):
        addresses = [x.strip() for x in config.FEEDBACK_RECIPIENT_LIST.split(',') if validate_email_wrapper(x.strip())]
        if addresses:
            current_site = get_current_site(self.request)
            data = form.cleaned_data
            data.update({
                'site': current_site.domain,
            })
            user = self.request.user
            if user.is_authenticated:
                data.update({
                    'rol': user.user_type_value,
                    'email': '%s%s%s' % (
                        data.get('email', ''),
                        ', ' if data.get('email') else '',
                        user.username,
                    )
                })
                if user.first_name or user.last_name:
                    data.update({
                        'name': user.get_full_name()
                    })
            body = render_to_string('feedback/mail/feedback.txt', data)
            sg = sendgrid.SendGridAPIClient(settings.SENDGRID_KEY)
            email = Mail(
                from_email='no-reply@%s' % current_site.domain,
                to_emails=addresses,
                subject='Omslagroute - feedback',
                plain_text_content=body
            )
            sg.send(email)
        else:
            return HttpResponseRedirect('./?error=1')
        return super().form_valid(form)

app/web/feedback/templates/feedback/feedback.html
{% extends 'base.html' %}

{% block feedback %}{% endblock %}
{% block header %}{% endblock %}

{% block title %} - Stuur ons je feedback{% endblock %}

{% block main %}
<div class="content-container feedback-container">
    <button data-handler="modal-close" class="button button--close">
    <svg width="20" height="20" title="Sluit venster">
        <use href="#close" xlink:href="#close" width="20" height="20"></use>
    </svg>
    <span class="sr-only">Sluit venster</span>
</button>
{% if request.GET.send %}
    <h2>Bedankt voor je feedback</h2>
    <hr class="" />
    <p>We hebben je feedback succesvol onvangen.</p>
    <div class="form-field form-field--buttons screen-only">
        <a data-handler="modal-close" href="#" class="button button--primary">Ga door waar ik mee bezig was</a>
    </div>

{% elif request.GET.error %}

    <h2>Er is iets mis gegaan</h2>
    <hr class="" />
    <p>Je feedback is helaas niet goed verstuurd.</p>
    <div class="form-field form-field--buttons screen-only">
        <a href="." class="button button--primary">Probeer het nog een keer</a>
        <a data-handler="modal-close" href="#" class="button button--secondary">Ga door waar ik mee bezig was</a>
    </div>

{% else %}

    <h2>Stuur ons je feedback</h2>
    <hr class="" />
    <p>Geef problemen, fouten of suggesties voor verbeteringen door.</p>
    <form method="post" novalidate>
        {% csrf_token %}

        <div class="form-field--textinput form-field form-field--empty">

            <label for="id_name">Naam <small class="help-text">(Optioneel)</small>:</label>
            {{ form.name }}
        </div>

        <div class="form-field--textinput form-field form-field--empty">
            <label for="id_email">E-mailadres <small class="help-text">(Optioneel)</small>:</label>
            <div class="help-text">Zodat we contact op kunnen nemen als we vragen hebben</div>
            {{ form.email }}
            {% if form.email.errors %}
                <ol class="error-text">
                {% for error in form.email.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
        <div class="form-field--textarea form-field form-field--empty">
            <label for="id_feedback">Wat wil je ons laten weten <small class="help-text">(Verplicht)</small>:</label>
            {% if form.feedback.errors %}{% endif %}
            {{ form.feedback }}
            {% if form.feedback.errors %}
                <ol class="error-text">
                {% for error in form.feedback.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>

        <div class="form-field form-field--buttons screen-only u-margin-top-3x">
            <input type="submit" value="Verstuur" class="button button--primary">
            <a data-handler="modal-close" href="#" class="button button--secondary">Annuleren</a>
        </div>
    </form>

{% endif %}
</div>
{% endblock %}

app/web/feedback/templates/feedback/feedback_context.html
<div class="container-button--feedback">
  <button
    class="button button--primary"
    data-handler="modal"
    data-contentid="modalFeedback"
  >
    Uw mening
  </button>
</div>

<div role="dialog" class="modal" id="modalFeedback">
  <iframe class="modal--feedback" id="iframeFeedback" data-src="{% url 'feedback' %}" src="about:blank" title="Geef uw mening">
  </iframe>
</div>